name: Update Medium posts in README

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull in Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@qaisartanvir"
          max_post_count: 3
          commit_message: "Update README with latest Medium posts"

          # Extract fields
          custom_tags: |
            postImage/content:encoded/<img.*?src=['"](.*?)['"]/\\1/
            postDesc/content:encoded/<p>(.*?)<\/p>/\\1/
            postTags/category/(.*)/\\1/

          # Display template
          template: |
            <a href="$url" target="_blank">
              <img src="$postImage" alt="$title" width="400"/>
            </a>  
            <br/>  
            <b><a href="$url" target="_blank">$title</a></b>  
            <br/>  
            $postDesc  
            <br/>  
            <i>Tags:</i> $postTags  
            <br/><br/>
