name: Latest blog post workflow (Medium)

on:
  schedule:
    - cron: "0 0 * * *"  # every 5 minutes for testing
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    name: Update README with latest Medium posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@qaisartanvir"
          max_post_count: 3
          disable_html_encoding: true
          # Map Medium's content:encoded into two custom fields we will process
          custom_tags: "postImage/content:encoded/,postDesc/content:encoded/"
          # Render categories as inline code pills
          categories_template: "<code>$category</code> "
          # Extract image URL + first paragraph (plain text) from content:encoded
          item_exec: >
            const html = (post.postImage || '');
            const mImg = html.match(/<img[^>]+src="([^"]+)"/i);
            post.postImage = mImg ? mImg[1] : '';
            const html2 = (post.postDesc || '');
            const mP = html2.match(/<p>(.*?)<\/p>/i);
            post.postDesc = mP
              ? mP[1].replace(/<[^>]+>/g,'').replace(/&nbsp;/g,' ').trim()
              : '';
            // Titles to skip
            const skipTitles = [
              "RealZoo",
              "How to download Torrent"
            ];
            if (skipTitles.some(t => post.title.toLowerCase().includes(t.toLowerCase()))) {
              post = null;
            }
          # Your custom template
          template: |
            <table>
              <tr>
                <td width="220" valign="top">
                  <a href="$url" target="_blank">
                    <img src="$postImage" alt="$title" width="200"/>
                  </a>
                </td>
                <td valign="top">
                  <b><a href="$url" target="_blank">$title</a></b><br/>
                  <p>$postDesc</p>
                  <i>Tags:</i> $categories
                </td>
              </tr>
            </table>
            <br/>
          commit_message: "chore: update README with latest Medium posts"
